databases:
  - name: portfolio_postgre
    databaseName: portfolio_postgre_vkki
    user: portfolio_postgre_vkki_user
    plan: free

services:
  - type: web
    name: Portfolio_deploy
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "./bin/rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "./bin/rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio_postgre
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
